cmake_minimum_required(VERSION 2.6)

option(VULKAN_RENDER_SYSTEM_ENABLED "Enable Vulkan API" ON)
option(VKE_RENDERER_DEBUG "Enable debugging of RenderSystem" ON)
option(VKE_SCENE_DEBUG "Enable debugging of SceneSystem" ON)
option(VKE_USE_DIRECTX_MATH "Enable math using DirectXMath" ON)
option(VKE_USE_SSE2 "Enable SSE2" ON)
option(VKE_USE_SSE3 "Enable SSE3" ON)
option(VKE_USE_SSE4 "Enable SSE4" ON)
option(VKE_USE_AVX "Enable AVX" ON)
option(VKE_USE_NEON "Enable NEON for ARM" OFF)
option(VKE_USE_RIGHT_HANDED_COORDINATES "Enable use of right handed coordinate system for RenderSystem" ON)
option(VKE_USE_XINPUT "Enable XINPUT for input device support" OFF)
option(BUILD_SAMPLES_ENABLED "Enable sample projects" ON)
if(VKE_WINDOWS)
    message( "windows" )
    option(VKE_USE_DIRECTXTEX "Enable image supported by DirectXTex" ON)
    option(VKE_USE_DEVIL "Enable image supported by DevIL" OFF)
else()
    option(VKE_USE_DIRECTXTEX "Enable image supported by DirectXTex" OFF)
    option(VKE_USE_DEVIL "Enable image supported by DevIL" ON)
endif()