cmake_minimum_required(VERSION 2.6)

function(SetOption option desc default define)
	option(${option} ${desc} ${default})
	if( ${option} and ${define} )
		add_definitions("-D${option}=1")
	else()
		add_definitions("-D${option}=0")
	endif()
endfunction()

option(VKE_DEBUG_INFO "Enables compilation debug info" ON)
option(VKE_VULKAN_RENDER_SYSTEM "Enable Vulkan API" ON)
option(VKE_RENDERER_DEBUG "Enable debugging of RenderSystem" ON)
option(VKE_SCENE_DEBUG "Enable debugging of SceneSystem" ON)
option(VKE_USE_DIRECTX_MATH "Enable math using DirectXMath" ON)
option(VKE_USE_SSE2 "Enable SSE2" ON)
option(VKE_USE_SSE3 "Enable SSE3" ON)
option(VKE_USE_SSE4 "Enable SSE4" ON)
option(VKE_USE_AVX "Enable AVX" ON)
option(VKE_USE_NEON "Enable NEON for ARM" OFF)
option(VKE_USE_RIGHT_HANDED_COORDINATES "Enable use of right handed coordinate system for RenderSystem" OFF)
option(VKE_USE_XINPUT "Enable XINPUT for input device support" OFF)
option(BUILD_SAMPLES_ENABLED "Enable sample projects" ON)
option(VKE_USE_HLSL_SYNTAX "Use HLSL shader syntax for DirectX Shader Compiler or glslang." ON)
option(VKE_USE_GAINPUT "Use Gainput lib for input." OFF)
option(VKE_USE_RAW_INPUT "Use RAW OS input." ON)
option(VKE_SCENE_TERRAIN_DEBUG "Terrain rendering debug mode." OFF)
option(VKE_ASSERT_ENABLE "Enable asserts in debug compilation." ON)
option(VKE_RENDER_SYSTEM_MEMORY_DEBUG "Enable additional info for GPU driver provided memory heaps." OFF)
option(VKE_MEMORY_DEBUG "Enable additional info for memory managers." OFF)

if(VKE_WINDOWS)
    message( "windows" )
    option(VKE_USE_DIRECTXTEX "Enable image supported by DirectXTex" ON)
    option(VKE_USE_DEVIL "Enable image supported by DevIL" OFF)
    option(VKE_USE_DIRECTX_SHADER_COMPILER "Enable DirectXShaderCompiler" ON)
    option(VKE_USE_GLSL_COMPILER "Enable glslang compiler" OFF)
else()
    option(VKE_USE_DIRECTXTEX "Enable image supported by DirectXTex" OFF)
    option(VKE_USE_DEVIL "Enable image supported by DevIL" ON)
    option(VKE_USE_DIRECTX_SHADER_COMPILER "Enable DirectXShaderCompiler" OFF)
    option(VKE_USE_GLSL_COMPILER "Enable glslang compiler" ON)
endif()