#pragma once

// Some newer DXGI_FORMAT enumerators are not defined by older/MinGW dxgiformat.h.
// Provide fallback values matching the official Windows SDK definitions.
#ifndef DXGI_FORMAT_SAMPLER_FEEDBACK_MIN_MIP_OPAQUE
#   define DXGI_FORMAT_SAMPLER_FEEDBACK_MIN_MIP_OPAQUE ( (DXGI_FORMAT)189 )
#endif
#ifndef DXGI_FORMAT_SAMPLER_FEEDBACK_MIP_REGION_USED_OPAQUE
#   define DXGI_FORMAT_SAMPLER_FEEDBACK_MIP_REGION_USED_OPAQUE ( (DXGI_FORMAT)190 )
#endif

namespace VKE::RenderSystem::D3D12
{
    static const DXGI_FORMAT g_aFormats[] = {
        // DX12 format mappings for VKE::RenderSystem::Formats::FORMAT
        DXGI_FORMAT_UNKNOWN,              // VK_FORMAT_UNDEFINED
        DXGI_FORMAT_UNKNOWN,              // VK_FORMAT_R4G4_UNORM_PACK8
        DXGI_FORMAT_UNKNOWN,              // VK_FORMAT_R4G4B4A4_UNORM_PACK16
        DXGI_FORMAT_UNKNOWN,              // VK_FORMAT_B4G4R4A4_UNORM_PACK16
        DXGI_FORMAT_UNKNOWN,              // VK_FORMAT_R5G6B5_UNORM_PACK16
        DXGI_FORMAT_UNKNOWN,              // VK_FORMAT_B5G6R5_UNORM_PACK16
        DXGI_FORMAT_UNKNOWN,              // VK_FORMAT_R5G5B5A1_UNORM_PACK16
        DXGI_FORMAT_UNKNOWN,              // VK_FORMAT_B5G5R5A1_UNORM_PACK16
        DXGI_FORMAT_UNKNOWN,              // VK_FORMAT_A1R5G5B5_UNORM_PACK16
        DXGI_FORMAT_R8_UNORM,             // VK_FORMAT_R8_UNORM
        DXGI_FORMAT_R8_SNORM,             // VK_FORMAT_R8_SNORM
        DXGI_FORMAT_UNKNOWN,              // VK_FORMAT_R8_USCALED
        DXGI_FORMAT_UNKNOWN,              // VK_FORMAT_R8_SSCALED
        DXGI_FORMAT_R8_UINT,              // VK_FORMAT_R8_UINT
        DXGI_FORMAT_R8_SINT,              // VK_FORMAT_R8_SINT
        DXGI_FORMAT_UNKNOWN,              // VK_FORMAT_R8_SRGB
        DXGI_FORMAT_R8G8_UNORM,           // VK_FORMAT_R8G8_UNORM
        DXGI_FORMAT_R8G8_SNORM,           // VK_FORMAT_R8G8_SNORM
        DXGI_FORMAT_UNKNOWN,              // VK_FORMAT_R8G8_USCALED
        DXGI_FORMAT_UNKNOWN,              // VK_FORMAT_R8G8_SSCALED
        DXGI_FORMAT_R8G8_UINT,            // VK_FORMAT_R8G8_UINT
        DXGI_FORMAT_R8G8_SINT,            // VK_FORMAT_R8G8_SINT
        DXGI_FORMAT_UNKNOWN,              // VK_FORMAT_R8G8_SRGB
        DXGI_FORMAT_UNKNOWN,              // VK_FORMAT_R8G8B8_UNORM
        DXGI_FORMAT_UNKNOWN,              // VK_FORMAT_R8G8B8_SNORM
        DXGI_FORMAT_UNKNOWN,              // VK_FORMAT_R8G8B8_USCALED
        DXGI_FORMAT_UNKNOWN,              // VK_FORMAT_R8G8B8_SSCALED
        DXGI_FORMAT_UNKNOWN,              // VK_FORMAT_R8G8B8_UINT
        DXGI_FORMAT_UNKNOWN,              // VK_FORMAT_R8G8B8_SINT
        DXGI_FORMAT_UNKNOWN,              // VK_FORMAT_R8G8B8_SRGB
        DXGI_FORMAT_UNKNOWN,              // VK_FORMAT_B8G8R8_UNORM
        DXGI_FORMAT_UNKNOWN,              // VK_FORMAT_B8G8R8_SNORM
        DXGI_FORMAT_UNKNOWN,              // VK_FORMAT_B8G8R8_USCALED
        DXGI_FORMAT_UNKNOWN,              // VK_FORMAT_B8G8R8_SSCALED
        DXGI_FORMAT_UNKNOWN,              // VK_FORMAT_B8G8R8_UINT
        DXGI_FORMAT_UNKNOWN,              // VK_FORMAT_B8G8R8_SINT
        DXGI_FORMAT_UNKNOWN,              // VK_FORMAT_B8G8R8_SRGB
        DXGI_FORMAT_R8G8B8A8_UNORM,       // VK_FORMAT_R8G8B8A8_UNORM
        DXGI_FORMAT_R8G8B8A8_SNORM,       // VK_FORMAT_R8G8B8A8_SNORM
        DXGI_FORMAT_UNKNOWN,              // VK_FORMAT_R8G8B8A8_USCALED
        DXGI_FORMAT_UNKNOWN,              // VK_FORMAT_R8G8B8A8_SSCALED
        DXGI_FORMAT_R8G8B8A8_UINT,        // VK_FORMAT_R8G8B8A8_UINT
        DXGI_FORMAT_R8G8B8A8_SINT,        // VK_FORMAT_R8G8B8A8_SINT
        DXGI_FORMAT_R8G8B8A8_UNORM_SRGB,  // VK_FORMAT_R8G8B8A8_SRGB
        DXGI_FORMAT_B8G8R8A8_UNORM,       // VK_FORMAT_B8G8R8A8_UNORM
        DXGI_FORMAT_UNKNOWN,              // VK_FORMAT_B8G8R8A8_SNORM
        DXGI_FORMAT_UNKNOWN,              // VK_FORMAT_B8G8R8A8_USCALED
        DXGI_FORMAT_UNKNOWN,              // VK_FORMAT_B8G8R8A8_SSCALED
        DXGI_FORMAT_UNKNOWN,              // VK_FORMAT_B8G8R8A8_UINT
        DXGI_FORMAT_UNKNOWN,              // VK_FORMAT_B8G8R8A8_SINT
        DXGI_FORMAT_B8G8R8A8_UNORM_SRGB,  // VK_FORMAT_B8G8R8A8_SRGB
        DXGI_FORMAT_UNKNOWN,              // VK_FORMAT_A8B8G8R8_UNORM_PACK32
        DXGI_FORMAT_UNKNOWN,              // VK_FORMAT_A8B8G8R8_SNORM_PACK32
        DXGI_FORMAT_UNKNOWN,              // VK_FORMAT_A8B8G8R8_USCALED_PACK32
        DXGI_FORMAT_UNKNOWN,              // VK_FORMAT_A8B8G8R8_SSCALED_PACK32
        DXGI_FORMAT_UNKNOWN,              // VK_FORMAT_A8B8G8R8_UINT_PACK32
        DXGI_FORMAT_UNKNOWN,              // VK_FORMAT_A8B8G8R8_SINT_PACK32
        DXGI_FORMAT_UNKNOWN,              // VK_FORMAT_A8B8G8R8_SRGB_PACK32
        DXGI_FORMAT_UNKNOWN,              // VK_FORMAT_A2R10G10B10_UNORM_PACK32
        DXGI_FORMAT_UNKNOWN,              // VK_FORMAT_A2R10G10B10_SNORM_PACK32
        DXGI_FORMAT_UNKNOWN,              // VK_FORMAT_A2R10G10B10_USCALED_PACK32
        DXGI_FORMAT_UNKNOWN,              // VK_FORMAT_A2R10G10B10_SSCALED_PACK32
        DXGI_FORMAT_UNKNOWN,              // VK_FORMAT_A2R10G10B10_UINT_PACK32
        DXGI_FORMAT_UNKNOWN,              // VK_FORMAT_A2R10G10B10_SINT_PACK32
        DXGI_FORMAT_UNKNOWN,              // VK_FORMAT_A2B10G10R10_UNORM_PACK32
        DXGI_FORMAT_UNKNOWN,              // VK_FORMAT_A2B10G10R10_SNORM_PACK32
        DXGI_FORMAT_UNKNOWN,              // VK_FORMAT_A2B10G10R10_USCALED_PACK32
        DXGI_FORMAT_UNKNOWN,              // VK_FORMAT_A2B10G10R10_SSCALED_PACK32
        DXGI_FORMAT_UNKNOWN,              // VK_FORMAT_A2B10G10R10_UINT_PACK32
        DXGI_FORMAT_UNKNOWN,              // VK_FORMAT_A2B10G10R10_SINT_PACK32
        DXGI_FORMAT_R16_UNORM,            // VK_FORMAT_R16_UNORM
        DXGI_FORMAT_R16_SNORM,            // VK_FORMAT_R16_SNORM
        DXGI_FORMAT_UNKNOWN,              // VK_FORMAT_R16_USCALED
        DXGI_FORMAT_UNKNOWN,              // VK_FORMAT_R16_SSCALED
        DXGI_FORMAT_R16_UINT,             // VK_FORMAT_R16_UINT
        DXGI_FORMAT_R16_SINT,             // VK_FORMAT_R16_SINT
        DXGI_FORMAT_R16_FLOAT,            // VK_FORMAT_R16_SFLOAT
        DXGI_FORMAT_R16G16_UNORM,         // VK_FORMAT_R16G16_UNORM
        DXGI_FORMAT_R16G16_SNORM,         // VK_FORMAT_R16G16_SNORM
        DXGI_FORMAT_UNKNOWN,              // VK_FORMAT_R16G16_USCALED
        DXGI_FORMAT_UNKNOWN,              // VK_FORMAT_R16G16_SSCALED
        DXGI_FORMAT_R16G16_UINT,          // VK_FORMAT_R16G16_UINT
        DXGI_FORMAT_R16G16_SINT,          // VK_FORMAT_R16G16_SINT
        DXGI_FORMAT_R16G16_FLOAT,         // VK_FORMAT_R16G16_SFLOAT
        DXGI_FORMAT_UNKNOWN,              // VK_FORMAT_R16G16B16_UNORM
        DXGI_FORMAT_UNKNOWN,              // VK_FORMAT_R16G16B16_SNORM
        DXGI_FORMAT_UNKNOWN,              // VK_FORMAT_R16G16B16_USCALED
        DXGI_FORMAT_UNKNOWN,              // VK_FORMAT_R16G16B16_SSCALED
        DXGI_FORMAT_UNKNOWN,              // VK_FORMAT_R16G16B16_UINT
        DXGI_FORMAT_UNKNOWN,              // VK_FORMAT_R16G16B16_SINT
        DXGI_FORMAT_UNKNOWN,              // VK_FORMAT_R16G16B16_SFLOAT
        DXGI_FORMAT_R16G16B16A16_UNORM,   // VK_FORMAT_R16G16B16A16_UNORM
        DXGI_FORMAT_R16G16B16A16_SNORM,   // VK_FORMAT_R16G16B16A16_SNORM
        DXGI_FORMAT_UNKNOWN,              // VK_FORMAT_R16G16B16A16_USCALED
        DXGI_FORMAT_UNKNOWN,              // VK_FORMAT_R16G16B16A16_SSCALED
        DXGI_FORMAT_R16G16B16A16_UINT,    // VK_FORMAT_R16G16B16A16_UINT
        DXGI_FORMAT_R16G16B16A16_SINT,    // VK_FORMAT_R16G16B16A16_SINT
        DXGI_FORMAT_R16G16B16A16_FLOAT,   // VK_FORMAT_R16G16B16A16_SFLOAT
        DXGI_FORMAT_R32_UINT,             // VK_FORMAT_R32_UINT
        DXGI_FORMAT_R32_SINT,             // VK_FORMAT_R32_SINT
        DXGI_FORMAT_R32_FLOAT,            // VK_FORMAT_R32_SFLOAT
        DXGI_FORMAT_R32G32_UINT,          // VK_FORMAT_R32G32_UINT
        DXGI_FORMAT_R32G32_SINT,          // VK_FORMAT_R32G32_SINT
        DXGI_FORMAT_R32G32_FLOAT,         // VK_FORMAT_R32G32_SFLOAT
        DXGI_FORMAT_R32G32B32_UINT,       // VK_FORMAT_R32G32B32_UINT
        DXGI_FORMAT_R32G32B32_SINT,       // VK_FORMAT_R32G32B32_SINT
        DXGI_FORMAT_R32G32B32_FLOAT,      // VK_FORMAT_R32G32B32_SFLOAT
        DXGI_FORMAT_R32G32B32A32_UINT,    // VK_FORMAT_R32G32B32A32_UINT
        DXGI_FORMAT_R32G32B32A32_SINT,    // VK_FORMAT_R32G32B32A32_SINT
        DXGI_FORMAT_R32G32B32A32_FLOAT,   // VK_FORMAT_R32G32B32A32_SFLOAT
        DXGI_FORMAT_UNKNOWN,              // VK_FORMAT_R64_UINT
        DXGI_FORMAT_UNKNOWN,              // VK_FORMAT_R64_SINT
        DXGI_FORMAT_UNKNOWN,              // VK_FORMAT_R64_SFLOAT
        DXGI_FORMAT_UNKNOWN,              // VK_FORMAT_R64G64_UINT
        DXGI_FORMAT_UNKNOWN,              // VK_FORMAT_R64G64_SINT
        DXGI_FORMAT_UNKNOWN,              // VK_FORMAT_R64G64_SFLOAT
        DXGI_FORMAT_UNKNOWN,              // VK_FORMAT_R64G64B64_UINT
        DXGI_FORMAT_UNKNOWN,              // VK_FORMAT_R64G64B64_SINT
        DXGI_FORMAT_UNKNOWN,              // VK_FORMAT_R64G64B64_SFLOAT
        DXGI_FORMAT_UNKNOWN,              // VK_FORMAT_R64G64B64A64_UINT
        DXGI_FORMAT_UNKNOWN,              // VK_FORMAT_R64G64B64A64_SINT
        DXGI_FORMAT_UNKNOWN,              // VK_FORMAT_R64G64B64A64_SFLOAT
        DXGI_FORMAT_UNKNOWN,              // VK_FORMAT_B10G11R11_UFLOAT_PACK32
        DXGI_FORMAT_UNKNOWN,              // VK_FORMAT_E5B9G9R9_UFLOAT_PACK32
        DXGI_FORMAT_D16_UNORM,            // VK_FORMAT_D16_UNORM
        DXGI_FORMAT_D24_UNORM_S8_UINT,    // VK_FORMAT_X8_D24_UNORM_PACK32
        DXGI_FORMAT_D32_FLOAT,            // VK_FORMAT_D32_SFLOAT
        DXGI_FORMAT_UNKNOWN,              // VK_FORMAT_S8_UINT
        DXGI_FORMAT_UNKNOWN,              // VK_FORMAT_D16_UNORM_S8_UINT
        DXGI_FORMAT_D24_UNORM_S8_UINT,    // VK_FORMAT_D24_UNORM_S8_UINT
        DXGI_FORMAT_D32_FLOAT_S8X24_UINT, // VK_FORMAT_D32_SFLOAT_S8_UINT
        DXGI_FORMAT_UNKNOWN,              // VK_FORMAT_BC1_RGB_UNORM_BLOCK
        DXGI_FORMAT_UNKNOWN,              // VK_FORMAT_BC1_RGB_SRGB_BLOCK
        DXGI_FORMAT_BC1_UNORM,            // VK_FORMAT_BC1_RGBA_UNORM_BLOCK
        DXGI_FORMAT_BC1_UNORM_SRGB,       // VK_FORMAT_BC1_RGBA_SRGB_BLOCK
        DXGI_FORMAT_BC2_UNORM,            // VK_FORMAT_BC2_UNORM_BLOCK
        DXGI_FORMAT_BC2_UNORM_SRGB,       // VK_FORMAT_BC2_SRGB_BLOCK
        DXGI_FORMAT_BC3_UNORM,            // VK_FORMAT_BC3_UNORM_BLOCK
        DXGI_FORMAT_BC3_UNORM_SRGB,       // VK_FORMAT_BC3_SRGB_BLOCK
        DXGI_FORMAT_BC4_UNORM,            // VK_FORMAT_BC4_UNORM_BLOCK
        DXGI_FORMAT_BC4_SNORM,            // VK_FORMAT_BC4_SNORM_BLOCK
        DXGI_FORMAT_BC5_UNORM,            // VK_FORMAT_BC5_UNORM_BLOCK
        DXGI_FORMAT_BC5_SNORM,            // VK_FORMAT_BC5_SNORM_BLOCK
        DXGI_FORMAT_BC6H_UF16,            // VK_FORMAT_BC6H_UFLOAT_BLOCK
        DXGI_FORMAT_BC6H_SF16,            // VK_FORMAT_BC6H_SFLOAT_BLOCK
        DXGI_FORMAT_BC7_UNORM,            // VK_FORMAT_BC7_UNORM_BLOCK
        DXGI_FORMAT_BC7_UNORM_SRGB,       // VK_FORMAT_BC7_SRGB_BLOCK
        DXGI_FORMAT_UNKNOWN,              // VK_FORMAT_ETC2_R8G8B8_UNORM_BLOCK
        DXGI_FORMAT_UNKNOWN,              // VK_FORMAT_ETC2_R8G8B8_SRGB_BLOCK
        DXGI_FORMAT_UNKNOWN,              // VK_FORMAT_ETC2_R8G8B8A1_UNORM_BLOCK
        DXGI_FORMAT_UNKNOWN,              // VK_FORMAT_ETC2_R8G8B8A1_SRGB_BLOCK
        DXGI_FORMAT_UNKNOWN,              // VK_FORMAT_ETC2_R8G8B8A8_UNORM_BLOCK
        DXGI_FORMAT_UNKNOWN,              // VK_FORMAT_ETC2_R8G8B8A8_SRGB_BLOCK
        DXGI_FORMAT_UNKNOWN,              // VK_FORMAT_EAC_R11_UNORM_BLOCK
        DXGI_FORMAT_UNKNOWN,              // VK_FORMAT_EAC_R11_SNORM_BLOCK
        DXGI_FORMAT_UNKNOWN,              // VK_FORMAT_EAC_R11G11_UNORM_BLOCK
        DXGI_FORMAT_UNKNOWN,              // VK_FORMAT_EAC_R11G11_SNORM_BLOCK
        DXGI_FORMAT_UNKNOWN,              // VK_FORMAT_ASTC_4x4_UNORM_BLOCK
        DXGI_FORMAT_UNKNOWN,              // VK_FORMAT_ASTC_4x4_SRGB_BLOCK
        DXGI_FORMAT_UNKNOWN,              // VK_FORMAT_ASTC_5x4_UNORM_BLOCK
        DXGI_FORMAT_UNKNOWN,              // VK_FORMAT_ASTC_5x4_SRGB_BLOCK
        DXGI_FORMAT_UNKNOWN,              // VK_FORMAT_ASTC_5x5_UNORM_BLOCK
        DXGI_FORMAT_UNKNOWN,              // VK_FORMAT_ASTC_5x5_SRGB_BLOCK
        DXGI_FORMAT_UNKNOWN,              // VK_FORMAT_ASTC_6x5_UNORM_BLOCK
        DXGI_FORMAT_UNKNOWN,              // VK_FORMAT_ASTC_6x5_SRGB_BLOCK
        DXGI_FORMAT_UNKNOWN,              // VK_FORMAT_ASTC_6x6_UNORM_BLOCK
        DXGI_FORMAT_UNKNOWN,              // VK_FORMAT_ASTC_6x6_SRGB_BLOCK
        DXGI_FORMAT_UNKNOWN,              // VK_FORMAT_ASTC_8x5_UNORM_BLOCK
        DXGI_FORMAT_UNKNOWN,              // VK_FORMAT_ASTC_8x5_SRGB_BLOCK
        DXGI_FORMAT_UNKNOWN,              // VK_FORMAT_ASTC_8x6_UNORM_BLOCK
        DXGI_FORMAT_UNKNOWN,              // VK_FORMAT_ASTC_8x6_SRGB_BLOCK
        DXGI_FORMAT_UNKNOWN,              // VK_FORMAT_ASTC_8x8_UNORM_BLOCK
        DXGI_FORMAT_UNKNOWN,              // VK_FORMAT_ASTC_8x8_SRGB_BLOCK
        DXGI_FORMAT_UNKNOWN,              // VK_FORMAT_ASTC_10x5_UNORM_BLOCK
        DXGI_FORMAT_UNKNOWN,              // VK_FORMAT_ASTC_10x5_SRGB_BLOCK
        DXGI_FORMAT_UNKNOWN,              // VK_FORMAT_ASTC_10x6_UNORM_BLOCK
        DXGI_FORMAT_UNKNOWN,              // VK_FORMAT_ASTC_10x6_SRGB_BLOCK
        DXGI_FORMAT_UNKNOWN,              // VK_FORMAT_ASTC_10x8_UNORM_BLOCK
        DXGI_FORMAT_UNKNOWN,              // VK_FORMAT_ASTC_10x8_SRGB_BLOCK
        DXGI_FORMAT_UNKNOWN,              // VK_FORMAT_ASTC_10x10_UNORM_BLOCK
        DXGI_FORMAT_UNKNOWN,              // VK_FORMAT_ASTC_10x10_SRGB_BLOCK
        DXGI_FORMAT_UNKNOWN,              // VK_FORMAT_ASTC_12x10_UNORM_BLOCK
        DXGI_FORMAT_UNKNOWN,              // VK_FORMAT_ASTC_12x10_SRGB_BLOCK
        DXGI_FORMAT_UNKNOWN,              // VK_FORMAT_ASTC_12x12_UNORM_BLOCK
        DXGI_FORMAT_UNKNOWN,              // VK_FORMAT_ASTC_12x12_SRGB_BLOCK

        // DX specific formats
        DXGI_FORMAT_R32G32B32A32_TYPELESS,
        DXGI_FORMAT_R32G32B32_TYPELESS,
        DXGI_FORMAT_R16G16B16A16_TYPELESS,
        DXGI_FORMAT_R32G32_TYPELESS,
        DXGI_FORMAT_R32G8X24_TYPELESS,
        DXGI_FORMAT_R32_FLOAT_X8X24_TYPELESS,
        DXGI_FORMAT_X32_TYPELESS_G8X24_UINT,
        DXGI_FORMAT_R10G10B10A2_TYPELESS,
        DXGI_FORMAT_R10G10B10A2_UNORM,
        DXGI_FORMAT_R10G10B10A2_UINT,
        DXGI_FORMAT_R11G11B10_FLOAT,
        DXGI_FORMAT_R8G8B8A8_TYPELESS,
        DXGI_FORMAT_R16G16_TYPELESS,
        DXGI_FORMAT_R32_TYPELESS,
        DXGI_FORMAT_R24G8_TYPELESS,
        DXGI_FORMAT_R24_UNORM_X8_TYPELESS,
        DXGI_FORMAT_X24_TYPELESS_G8_UINT,
        DXGI_FORMAT_R8G8_TYPELESS,
        DXGI_FORMAT_R16_TYPELESS,
        DXGI_FORMAT_R8_TYPELESS,
        DXGI_FORMAT_A8_UNORM,
        DXGI_FORMAT_R1_UNORM,
        DXGI_FORMAT_R9G9B9E5_SHAREDEXP,
        DXGI_FORMAT_R8G8_B8G8_UNORM,
        DXGI_FORMAT_G8R8_G8B8_UNORM,
        DXGI_FORMAT_BC1_TYPELESS,
        DXGI_FORMAT_BC2_TYPELESS,
        DXGI_FORMAT_BC3_TYPELESS,
        DXGI_FORMAT_BC4_TYPELESS,
        DXGI_FORMAT_BC5_TYPELESS,
        DXGI_FORMAT_B5G6R5_UNORM,
        DXGI_FORMAT_B5G5R5A1_UNORM,
        DXGI_FORMAT_B8G8R8X8_UNORM,
        DXGI_FORMAT_R10G10B10_XR_BIAS_A2_UNORM,
        DXGI_FORMAT_B8G8R8A8_TYPELESS,
        DXGI_FORMAT_B8G8R8X8_TYPELESS,
        DXGI_FORMAT_B8G8R8X8_UNORM_SRGB,
        DXGI_FORMAT_BC6H_TYPELESS,
        DXGI_FORMAT_BC7_TYPELESS,
        DXGI_FORMAT_AYUV,
        DXGI_FORMAT_Y410,
        DXGI_FORMAT_Y416,
        DXGI_FORMAT_NV12,
        DXGI_FORMAT_P010,
        DXGI_FORMAT_P016,
        DXGI_FORMAT_420_OPAQUE,
        DXGI_FORMAT_YUY2,
        DXGI_FORMAT_Y210,
        DXGI_FORMAT_Y216,
        DXGI_FORMAT_NV11,
        DXGI_FORMAT_AI44,
        DXGI_FORMAT_IA44,
        DXGI_FORMAT_P8,
        DXGI_FORMAT_A8P8,
        DXGI_FORMAT_B4G4R4A4_UNORM,
        DXGI_FORMAT_P208,
        DXGI_FORMAT_V208,
        DXGI_FORMAT_V408,
        DXGI_FORMAT_SAMPLER_FEEDBACK_MIN_MIP_OPAQUE,
        DXGI_FORMAT_SAMPLER_FEEDBACK_MIP_REGION_USED_OPAQUE,

    };

}; // namespace VKE::RenderSystem::D3D12